src/Entity/Export.php
<?php

namespace App\Entity;

use App\Repository\ExportRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ExportRepository::class)
 */
class Export
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $timestamp;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="exports")
     */
    private $user_id;

    /**
     * @ORM\ManyToOne(targetEntity=Institution::class, inversedBy="exports")
     */
    private $institution_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTimestamp(): ?\DateTimeInterface
    {
        return $this->timestamp;
    }

    public function setTimestamp(\DateTimeInterface $timestamp): self
    {
        $this->timestamp = $timestamp;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getInstitutionId(): ?Institution
    {
        return $this->institution_id;
    }

    public function setInstitutionId(?Institution $institution_id): self
    {
        $this->institution_id = $institution_id;

        return $this;
    }
}

src/Entity/Institution.php
<?php

namespace App\Entity;

use App\Repository\InstitutionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InstitutionRepository::class)
 */
class Institution
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity=Export::class, mappedBy="institution_id")
     */
    private $exports;

    public function __construct()
    {
        $this->exports = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Export>
     */
    public function getExports(): Collection
    {
        return $this->exports;
    }

    public function addExport(Export $export): self
    {
        if (!$this->exports->contains($export)) {
            $this->exports[] = $export;
            $export->setInstitutionId($this);
        }

        return $this;
    }

    public function removeExport(Export $export): self
    {
        if ($this->exports->removeElement($export)) {
            // set the owning side to null (unless already changed)
            if ($export->getInstitutionId() === $this) {
                $export->setInstitutionId(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 */
class User
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fullname;

    /**
     * @ORM\OneToMany(targetEntity=Export::class, mappedBy="user_id")
     */
    private $exports;

    public function __construct()
    {
        $this->exports = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullname(): ?string
    {
        return $this->fullname;
    }

    public function setFullname(string $fullname): self
    {
        $this->fullname = $fullname;

        return $this;
    }

    /**
     * @return Collection<int, Export>
     */
    public function getExports(): Collection
    {
        return $this->exports;
    }

    public function addExport(Export $export): self
    {
        if (!$this->exports->contains($export)) {
            $this->exports[] = $export;
            $export->setUserId($this);
        }

        return $this;
    }

    public function removeExport(Export $export): self
    {
        if ($this->exports->removeElement($export)) {
            // set the owning side to null (unless already changed)
            if ($export->getUserId() === $this) {
                $export->setUserId(null);
            }
        }

        return $this;
    }
}

src/Controller/ExportController.php
<?php

namespace App\Controller;

use App\Entity\Export;
use App\Entity\Institution;
use App\Entity\User;
use App\Repository\ExportRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class ExportController extends AbstractController
{
    public function __construct(ExportRepository $repository, EntityManagerInterface $entityManager)
    {
        $this->repository = $repository;
        $this->entityManager = $entityManager;
    }


    /**
     * @Route("/export", name="export")
     */
    public function index(EntityManagerInterface $entityManager): Response
    {
        $exports = $this->entityManager->getRepository(Export::class)->findAll();

        return $this->render('export/index.html.twig', [
            'exports'=>$exports
        ]);
    }


    /**
     * @return void
     * @Route("/filter",name="filter")
     */
    public function filters(Request $request)
    {
        $institutions = $this->entityManager->getRepository(Institution::class)->findAll();
        $filters = $request->request->get('filter');

//        dd($filters);

        return $this->render('export/index.html.twig', [
            'exports'=>$this->repository->filter($filters),
            'institutions'=>$institutions,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
            <style>
                #filters {display:-webkit-box;display:-ms-flexbox;display:flex; margin-bottom: 20px;}
                #filters div:not(:last-child) {margin-right: 20px;}
                #filters div label {display: block; width: 100%;}
            </style>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
            <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/export/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ExportController!{% endblock %}

{% block stylesheet %}

{% endblock %}

{% block body %}
    <div class="container">
        <form action="{{ path('filter') }}" class="row" method="POST">

            {% if institutions is not defined %}
                {% set institutions = [] %}

                {% for export in exports %}
                    {% if export.institutionId not in institutions %}
                        {% set institutions = institutions|merge([export.institutionId]) %}
                    {% endif %}
                {% endfor %}
            {% endif %}
            {% if app.request.get('filter') %}
                {% set q_institution_id = app.request.get('filter')['institution_id'] %}
                {% set q_from = app.request.get('filter')['timestamp']['from'] %}
                {% set q_to = app.request.get('filter')['timestamp']['to'] %}
            {% endif %}
            <nav id="filters">
                <div>
                    <label>Institution</label>
                    <select name="filter[institution_id]">
                        <option value="0">Wszystkie</option>
                        {% for institution in institutions %}
                            <option {% if q_institution_id is defined and q_institution_id == institution.id  %}selected{% endif %} value="{{ institution.id }}">{{ institution.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                    <label for="">From</label>
                    <input type="date" {% if q_from is defined %}value="{{ q_from }}"{% endif%} name="filter[timestamp][from]">
                </div>
                <div>
                    <label for="">To</label>
                    <input type="date" {% if q_to is defined %}value="{{ q_to }}"{% endif%} name="filter[timestamp][to]">
                </div>
            </nav>


            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Nazwa</th>
                    <th scope="col">Data</th>
                    <th scope="col">Godzina</th>
                    <th scope="col">Użytkownik</th>
                    <th scope="col">Lokal</th>
                </tr>
                </thead>
                <tbody>
                {% if exports|length %}
                    {% for export in exports %}
                        <tr>
                            <th scope="row">{{ export.name }}</th>
                            <td>{{ export.timestamp|date('Y-m-d') }}</td>
                            <td>{{ export.timestamp|date('H:i') }}</td>
                            <td>{{ export.userId.fullname }}</td>
                            <td>{{ export.institutionId.name }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td>Brak wyników</td>
                    </tr>
                {% endif %}

                </tbody>
            </table>
            <button class="btn btn-primary" type="submit">Zatwierdź</button>
        </form>
    </div>
{% endblock %}